# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('modalidade', models.CharField(choices=[('I', 'Educa\xe7\xe3o Infantil'), ('F', 'Ensino Fundamental'), ('M', 'Ensino M\xe9dio')], max_length=1)),
                ('ativa', models.BooleanField(default=True)),
                ('disciplinas', models.ManyToManyField(through='escola.Curriculo', to='escola.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('ativa', models.BooleanField(default=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie', to='escola.Serie')),
            ],
        ),
        migrations.AddField(
            model_name='curriculo',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Disciplina'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Serie'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set([('serie', 'sequencia')]),
        ),
        migrations.AlterUniqueTogether(
            name='serie',
            unique_together=set([('descricao', 'modalidade')]),
        ),
    ]
