# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 15:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ano_letivo', models.PositiveIntegerField()),
                ('parecer', models.CharField(default='111111/1111', max_length=255)),
                ('data_validade_parecer', models.DateField(default=datetime.datetime(2018, 4, 28, 15, 18, 43, 296499))),
            ],
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('base_nacional_comum', models.BooleanField(default=True)),
                ('somente_historico', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalConfiguracoes',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('media', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ano_letivo', models.PositiveIntegerField()),
                ('parecer', models.CharField(default='111111/1111', max_length=255)),
                ('data_validade_parecer', models.DateField(default=datetime.datetime(2018, 4, 28, 15, 18, 43, 296499))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical configuracoes',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCurriculo',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('disciplina', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.Disciplina')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical curriculo',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDisciplina',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('base_nacional_comum', models.BooleanField(default=True)),
                ('somente_historico', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical disciplina',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSerie',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descricao', models.CharField(choices=[('Infantil I', 'Infantil I'), ('Infantil II', 'Infantil II'), ('Infantil III', 'Infantil III'), ('Infantil IV', 'Infantil IV'), ('Infantil V', 'Infantil V'), ('1\xb0 Ano', '1\xb0 Ano'), ('2\xb0 Ano', '2\xb0 Ano'), ('3\xb0 Ano', '3\xb0 Ano'), ('4\xb0 Ano', '4\xb0 Ano'), ('5\xb0 Ano', '5\xb0 Ano'), ('6\xb0 Ano', '6\xb0 Ano'), ('7\xb0 Ano', '7\xb0 Ano'), ('8\xb0 Ano', '8\xb0 Ano'), ('9\xb0 Ano', '9\xb0 Ano')], max_length=255)),
                ('modalidade', models.CharField(choices=[('I', 'Educa\xe7\xe3o Infantil'), ('F', 'Ensino Fundamental'), ('M', 'Ensino M\xe9dio')], max_length=1)),
                ('ativa', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical serie',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTurma',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sequencia', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('ativa', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical turma',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(choices=[('Infantil I', 'Infantil I'), ('Infantil II', 'Infantil II'), ('Infantil III', 'Infantil III'), ('Infantil IV', 'Infantil IV'), ('Infantil V', 'Infantil V'), ('1\xb0 Ano', '1\xb0 Ano'), ('2\xb0 Ano', '2\xb0 Ano'), ('3\xb0 Ano', '3\xb0 Ano'), ('4\xb0 Ano', '4\xb0 Ano'), ('5\xb0 Ano', '5\xb0 Ano'), ('6\xb0 Ano', '6\xb0 Ano'), ('7\xb0 Ano', '7\xb0 Ano'), ('8\xb0 Ano', '8\xb0 Ano'), ('9\xb0 Ano', '9\xb0 Ano')], max_length=255)),
                ('modalidade', models.CharField(choices=[('I', 'Educa\xe7\xe3o Infantil'), ('F', 'Ensino Fundamental'), ('M', 'Ensino M\xe9dio')], max_length=1)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('ativa', models.BooleanField(default=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='escola.Serie')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='serie',
            unique_together=set([('descricao', 'modalidade')]),
        ),
        migrations.AddField(
            model_name='historicalturma',
            name='serie',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.Serie'),
        ),
        migrations.AddField(
            model_name='historicalcurriculo',
            name='serie',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.Serie'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Disciplina'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculos', to='escola.Serie'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set([('serie', 'sequencia')]),
        ),
        migrations.AlterUniqueTogether(
            name='curriculo',
            unique_together=set([('disciplina', 'serie', 'ativo')]),
        ),
    ]
