# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='descricao',
            field=models.IntegerField(choices=[(1, 'Infantil I'), (2, 'Infantil II'), (3, 'Infantil III'), (4, '1\xb0 Ano'), (5, '2\xb0 Ano'), (6, '3\xb0 Ano'), (7, '4\xb0 Ano'), (8, '5\xb0 Ano'), (9, '6\xb0 Ano'), (10, '7\xb0 Ano'), (11, '8\xb0 Ano'), (12, '9\xb0 Ano')]),
        ),
    ]
