# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_auto_20171215_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='descricao',
            field=models.CharField(choices=[('Infantil I', 'Infantil I'), ('Infantil II', 'Infantil II'), ('Infantil III', 'Infantil III'), ('1\xb0 Ano', '1\xb0 Ano'), ('2\xb0 Ano', '2\xb0 Ano'), ('3\xb0 Ano', '3\xb0 Ano'), ('4\xb0 Ano', '4\xb0 Ano'), ('5\xb0 Ano', '5\xb0 Ano'), ('6\xb0 Ano', '6\xb0 Ano'), ('7\xb0 Ano', '7\xb0 Ano'), ('8\xb0 Ano', '8\xb0 Ano'), ('9\xb0 Ano', '9\xb0 Ano')], max_length=255),
        ),
    ]
