# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_auto_20171215_1420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculo',
            unique_together=set([('disciplina', 'serie', 'ativo')]),
        ),
    ]
