# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_historicalconfiguracoes_historicalcurriculo_historicaldisciplina_historicalserie_historicalturma'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='base_nacional_comum',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaldisciplina',
            name='base_nacional_comum',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='escola.Serie'),
        ),
    ]
