# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_auto_20181116_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoes',
            name='data_validade_parecer',
            field=models.DateField(default=datetime.datetime(2018, 11, 29, 22, 33, 7, 997188)),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracoes',
            name='data_validade_parecer',
            field=models.DateField(default=datetime.datetime(2018, 11, 29, 22, 33, 7, 997188)),
        ),
    ]
