# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_auto_20180203_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculos', to='escola.Serie'),
        ),
    ]
