# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_auto_20180203_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='disciplinas',
        ),
    ]
