# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0016_auto_20180426_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoes',
            name='data_validade_parecer',
            field=models.DateField(default=datetime.datetime(2018, 4, 26, 15, 41, 11, 899588)),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracoes',
            name='data_validade_parecer',
            field=models.DateField(default=datetime.datetime(2018, 4, 26, 15, 41, 11, 899588)),
        ),
    ]
