# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0004_auto_20171216_1322'),
        ('aluno', '0002_auto_20171223_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tipo', models.CharField(choices=[(b'P', b'Nota Parcial'), (b'B', b'Nota Bimestral'), (b'R', b'Recupera\xc3\xa7\xc3\xa3o Paralela')], max_length=1)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina', to='escola.Disciplina')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='aluno.Matricula')),
            ],
        ),
    ]
