# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='bimestre',
            field=models.CharField(choices=[(1, b'1\xc2\xb0 Bimestre'), (2, b'2\xc2\xb0 Bimestre'), (3, b'3\xc2\xb0 Bimestre'), (4, b'4\xc2\xb0 Bimestre')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
