# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendimento', '0002_nota_bimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='bimestre',
            field=models.IntegerField(choices=[(1, b'1\xc2\xb0 Bimestre'), (2, b'2\xc2\xb0 Bimestre'), (3, b'3\xc2\xb0 Bimestre'), (4, b'4\xc2\xb0 Bimestre')], max_length=1),
        ),
    ]
