# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_auto_20171216_1322'),
        ('aluno', '0004_auto_20171227_2211'),
        ('rendimento', '0003_auto_20171226_1852'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set([('matricula', 'disciplina', 'bimestre', 'tipo')]),
        ),
    ]
