# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rendimento', '0007_auto_20180131_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Disciplina'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='aluno.Matricula'),
        ),
    ]
