# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 20:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0004_auto_20171216_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('nome_pai', models.CharField(max_length=255)),
                ('nome_mae', models.CharField(max_length=255)),
                ('nome_responsavel', models.CharField(max_length=255)),
                ('telefone', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.PositiveIntegerField()),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.PositiveIntegerField()),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(default=datetime.date(2017, 12, 22))),
                ('ano', models.PositiveIntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='aluno.Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma', to='escola.Turma')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='aluno.Endereco'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='matriculas',
            field=models.ManyToManyField(through='aluno.Matricula', to='escola.Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set([('aluno', 'turma', 'ano')]),
        ),
    ]
