# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='numero',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
