# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20171223_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(default=datetime.date(2017, 12, 26)),
        ),
    ]
