# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_historicalaluno_historicalendereco_historicalmatricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmatricula',
            name='numero',
            field=models.CharField(db_index=True, default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='numero',
            field=models.CharField(default='0', max_length=255, unique=True),
        ),
    ]
