# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_auto_20171228_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='matriculas',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(default=datetime.date(2018, 1, 16)),
        ),
    ]
