# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0007_auto_20180131_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.Endereco'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalendereco',
            name='cep',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalmatricula',
            name='data_matricula',
            field=models.DateField(default=datetime.date(2018, 2, 3)),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='aluno.Aluno'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(default=datetime.date(2018, 2, 3)),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='escola.Turma'),
        ),
    ]
