# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0008_auto_20180203_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmatricula',
            name='data_matricula',
            field=models.DateField(default=datetime.date(2018, 2, 7)),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(default=datetime.date(2018, 2, 7)),
        ),
    ]
