# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0010_auto_20180208_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmatricula',
            name='data_matricula',
            field=models.DateField(default=datetime.date(2018, 2, 15)),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(default=datetime.date(2018, 2, 15)),
        ),
    ]
