# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import util.utils


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0016_auto_20180407_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatricula',
            name='numero',
            field=models.CharField(db_index=True, default=util.utils.gerar_numero_matricula, max_length=255),
        ),
        migrations.AddField(
            model_name='matricula',
            name='numero',
            field=models.CharField(default=util.utils.gerar_numero_matricula, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalmatricula',
            name='data_matricula',
            field=models.DateField(default=datetime.date(2018, 4, 26)),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(default=datetime.date(2018, 4, 26)),
        ),
    ]
