# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0017_auto_20180426_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmatricula',
            name='data_matricula',
            field=models.DateField(default=datetime.date(2018, 4, 28)),
        ),
        migrations.AlterField(
            model_name='historicalmatricula',
            name='id',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmatricula',
            name='numero',
            field=models.CharField(db_index=True, default=b'188100<django.db.models.fields.AutoField>', max_length=255),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(default=datetime.date(2018, 4, 28)),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='numero',
            field=models.CharField(default=b'188100<django.db.models.fields.AutoField>', max_length=255, unique=True),
        ),
    ]
