# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0010_auto_20180208_2233'),
        ('escola', '0009_remove_serie_disciplinas'),
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='aluno.Aluno'),
        ),
        migrations.AlterUniqueTogether(
            name='historico',
            unique_together=set([('ano', 'serie', 'aluno')]),
        ),
    ]
