# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0011_auto_20180215_2112'),
        ('escola', '0009_remove_serie_disciplinas'),
        ('historico', '0002_auto_20180208_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='municipio',
            new_name='cidade',
        ),
        migrations.AlterUniqueTogether(
            name='historico',
            unique_together=set([('ano', 'serie', 'aluno', 'instituicao')]),
        ),
    ]
