# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0011_auto_20180215_2112'),
        ('historico', '0003_auto_20180215_2112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historico',
            unique_together=set([('ano', 'aluno')]),
        ),
        migrations.AlterUniqueTogether(
            name='instituicao',
            unique_together=set([('descricao',)]),
        ),
    ]
